run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - io.ReadAll
      - (io.Closer).Close
  
  govet:
    enable:
      - shadow
  
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam
    
    # Allow blank identifier for intentionally ignored errors
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
      source: "^\\s*_\\s*="
    
    # Allow blank identifier in defer closures
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
      source: "defer func\\(\\) \\{ _ ="
